  # A Docker web service
  - type: php
    name: icecoder
    env: docker
    repo: https://github.com/OxideCheats-Public/icecoder4.git # optional
    region: ohio # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: master # optional (defaults to master)
    rootDir: icecoder4
    dockerCommand: docker build -t icecoder/docker . # optional (defaults to Dockerfile command)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings
